In [ ]:
import numpy as np

match = 0
mismatch = -1
gap_penalty = -2
inf = -999

seqA = "ATCATC"
seqB = "TCAGTC"
n = len(seqA)
m = len(seqB)
matrix = np.full((n + 1, m + 1), inf)

# First 0,0
matrix[0,0] = 0

# First row and column only gaps are allowed each 3 nucleotides
for tri in range(3, n + 1, 3):
    matrix[0, tri] = tri * gap_penalty

for tri in range(3, n + 1, 3):
    matrix[tri, 0] = tri * gap_penalty

for i in range(1, n + 1):
    for j in range(1, m + 1):
        # Coming from diag:
        score_diag = matrix[i-1, j-1] + (match if seqA[i-1] == seqB[j-1] else mismatch)

        # Coming from vert
        options_vert = [inf]
        for k in range(3, i + 1, 3):
            options_vert.append(matrix[i - k ,j] + (gap_penalty * k))
        score_vert = max(options_vert)
        # Coming from horizont
        options_hori = [inf]
        for k in range(3, j + 1, 3):
            options_hori.append(matrix[i ,j - k] + (gap_penalty * k))
        score_hori = max(options_hori)

        matrix[i, j] = max(score_diag, score_vert, score_hori)

print(matrix)


[[   0 -999 -999   -6 -999 -999  -12]
 [-999   -1 -999 -999   -7 -999 -999]
 [-999 -999   -2 -999 -999   -7 -999]
 [  -6 -999 -999   -3 -999 -999   -7]
 [-999   -7 -999 -999   -4 -999 -999]
 [-999 -999   -8 -999 -999   -4 -999]
 [ -12 -999 -999   -9 -999 -999   -4]]
Final alignment:
ATCATC
TCAGTC
